name: Leadenhall Tailoring
favicon: null
layout_spectrum: 0.7564355118665844
typography_spectrum: 0.5159730170853436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffe7'
    - '#d1be86'
    - '#4e5e6e'
    - '#5e2102'
  brandStrength: 1
  lightness: 0.7353834153618664
  saturation: 0.20834848727099597
  rhythmicContrast: 0.635727162938565
purpose: []
